# Generated by Django 6.1.1 on 2026-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('descriptions', models.TextField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
